//
//  loginInteractor.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol loginBusinessLogic
{
  func doLogin(request: login.Login.Request)
}

protocol loginDataStore
{
  //var name: String { get set }
}

class loginInteractor: loginBusinessLogic, loginDataStore
{
  var presenter: loginPresentationLogic?
  var worker: loginWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doLogin(request: login.Login.Request){
    worker = loginWorker()
    worker?.doLogin(request: request)
    
    let response = login.Login.Response()
    presenter?.presentSomething(response: response)
  }
}
