//
//  loginWorker.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol loginWorkerDelegate {
    func passData(_: loginWorker, data: Any)
}



class loginWorker: APIResquestDelegate{

    var delegate: loginWorkerDelegate?
    var apiRequest: APIRequest? = APIRequest()
    
    func doLogin(request: login.Login.Request){
        apiRequest?.delegate = self
        apiRequest!.login(loginData: request)
    }
    
    func didRequestSuccess(_: APIRequest, data: Any) {
        DispatchQueue.main.async {
            self.delegate?.passData(self, data: data)
//            print(userData.cpf)
//            self.dataUser.populate(userData)
//            SVProgressHUD.dismiss()
//            self.btnLogin.isEnabled = true
//            self.keyChainSave()
//            self.performSegue(withIdentifier: "loginSegue", sender: self)
        }
    }
    
    func didRequestFailed(_: APIRequest, error: Error) {
        DispatchQueue.main.async {
            print(error)
//            SVProgressHUD.dismiss()
//            self.btnLogin.isEnabled = true
        }
    }
    
    func didResponseFailed(_: APIRequest, response: HTTPURLResponse) {
        DispatchQueue.main.async {
            if (response.statusCode == 401) {
//                let alert = UIAlertController(title: "Aviso", message: "Credenciais inválidas", preferredStyle: .alert)
//                alert.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: nil))
//                self.present(alert, animated: true, completion: nil)
            }else {
//                self.txtError.isHidden = false
            }
//            SVProgressHUD.dismiss()
//            self.btnLogin.isEnabled = true
        }
    }
    
}
