//
//  loginRouter.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol loginRoutingLogic
{
    func routeToStatement(segue: UIStoryboardSegue?)
}

protocol loginDataPassing
{
    var dataStore: loginDataStore? { get }
}

class loginRouter: NSObject, loginRoutingLogic, loginDataPassing
{
    weak var viewController: loginViewController?
    var dataStore: loginDataStore?
    
    // MARK: Routing
    
    func routeToStatement(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! statementViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToStatement(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "statementViewController") as! statementViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToStatement(source: dataStore!, destination: &destinationDS)
            navigateToStatement(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToStatement(source: loginViewController, destination: statementViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToStatement(source: loginDataStore, destination: inout statementDataStore)
    {
        //    destination.userData = source.name
    }
}
