//
//  loginInteractor.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol loginBusinessLogic
{
  func doLogin(request: login.Login.Request)
}

protocol loginDataStore
{
  //var name: String { get set }
}

class loginInteractor: loginBusinessLogic, loginDataStore, loginWorkerDelegate {

    var presenter: loginPresentationLogic?
    var worker: loginWorker? = loginWorker()
    //var name: String = ""

    // MARK: Do something

    func doLogin(request: login.Login.Request){
        worker?.delegate = self
        worker?.doLogin(request: request)
    }
    
    func passData(_: loginWorker, data: Any) {
        let userData = data as! APIModels.APIRequestLogin
        let user = UserModel(name: userData.nome, cpf: userData.cpf, balance: userData.saldo, token: userData.token)
        let response = login.Login.Response(user: user)
        presenter?.presentSomething(response: response)
    }
}
