//
//  loginModels.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum login
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
        let login: String
        let password: String
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
