//
//  statementRouter.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol statementRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol statementDataPassing
{
  var dataStore: statementDataStore? { get }
}

class statementRouter: NSObject, statementRoutingLogic, statementDataPassing
{
  weak var viewController: statementViewController?
  var dataStore: statementDataStore?
  
  // MARK: Routing
  
//  func routeToSomewhere(segue: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! loginViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "loginViewController") as! loginViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//  }

  // MARK: Navigation
  
//  func navigateToSomewhere(source: statementViewController, destination: loginViewController)
//  {
//    source.show(destination, sender: nil)
//  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: statementDataStore, destination: inout loginViewController)
//  {
//    destination.name = source.name
//  }
}
