//
//  statementPresenter.swift
//  CleanSwift
//
//  Created by Virtual Machine on 14/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol statementPresentationLogic
{
  func presentSomething(response: statement.Something.Response)
}

class statementPresenter: statementPresentationLogic
{
  weak var viewController: statementDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: statement.Something.Response)
  {
    let viewModel = statement.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
